spring:
  datasource:
    url: jdbc:h2:mem:eagerlazy;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: always
      defer-datasource-initialization: true   # 👈 fixes timing issue
  h2:
    console:
      enabled: true
      path: /h2
